[package]
name = "prisma-rust-schema"
version = "0.1.0"
edition = "2024"
authors = ["Shaun Hamilton <shauhami020@gmail.com>"]
description = "A Rust binary to act as a Prisma generator, generating Rust code from Prisma schema files."
license = "MIT"
readme = "README.md"
repository = "https://github.com/ShaunSHamilton/prisma-rust-schema/"


[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
serde_path_to_error = "0.1.17"
