name: Prisma Compatibility

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test Prisma v${{ matrix.prisma_version }} / Rust ${{ matrix.rust }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # v5 works, but is not tested against, because native types do not exist
        prisma_version: ["6"]
        rust: ["stable"]

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust Toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y nodejs npm

      - name: Install Prisma CLI
        run: npm install -g prisma@${{ matrix.prisma_version }}

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Run Tests
        run: cargo test
